# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(max_length=256)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image_url_sm', models.URLField(blank=True)),
                ('image_url_med', models.URLField(blank=True)),
                ('image_url_lg', models.URLField(blank=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.IntegerField(choices=[(0, b'Unknown'), (1, b'In Inventory'), (2, b'Checked Out'), (3, b'Loaned'), (4, b'Removed from Inventory Permanently')], default=0)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mt.Asset')),
            ],
        ),
    ]
