# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='image_url_lg',
            new_name='large_img',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='image_url_med',
            new_name='medium_img',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='image_url_sm',
            new_name='small_img',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='barcode',
            new_name='upc',
        ),
    ]
