# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0002_auto_20160911_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='actors',
            field=models.ManyToManyField(to='mt.Person'),
        ),
    ]
