# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0005_auto_20160911_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
