# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0005_auto_20160806_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='trans',
            field=models.IntegerField(choices=[(0, b'Unknown'), (1, b'In Inventory'), (2, b'Checked Out'), (3, b'Loaned'), (4, b'Removed from Inventory Permanently')], default=0),
        ),
    ]
