# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mt', '0006_auto_20160806_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieasset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
