# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0008_remove_asset_binding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
    ]
