# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0009_remove_asset_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='features',
        ),
    ]
