# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0010_remove_asset_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asin',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='asset',
            name='binding',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='asset',
            name='features',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
