# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0011_auto_20160913_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asin',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='binding',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='features',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='large_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='medium_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='small_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
