# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0012_auto_20160913_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='actor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='director',
            field=models.BooleanField(default=False),
        ),
    ]
