# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0013_auto_20160915_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='directors',
        ),
    ]
