# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0014_auto_20160915_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='features',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
